"""Add SearchSession table

Revision ID: 50932ab33e1b
Revises: 001
Create Date: 2026-05-25 20:10:17.585486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50932ab33e1b'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('criteria', sa.Text(), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_sessions_user_id'), 'search_sessions', ['user_id'], unique=False)
    op.create_index('ix_search_sessions_user_id_created_at', 'search_sessions', ['user_id', 'created_at'], unique=False)
    op.alter_column('cv_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cv_files', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cv_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('evaluations', 'evaluated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('jobs', 'discovered_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('evaluations', 'evaluated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cv_files', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cv_files', 'ingested_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('cv_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index('ix_search_sessions_user_id_created_at', table_name='search_sessions')
    op.drop_index(op.f('ix_search_sessions_user_id'), table_name='search_sessions')
    op.drop_table('search_sessions')
    # ### end Alembic commands ###
