"""add unique constraint evaluations user job

Revision ID: 6cfe28947e05
Revises: 50932ab33e1b
Create Date: 2026-06-01 10:23:03.362268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cfe28947e05'
down_revision: Union[str, Sequence[str], None] = '50932ab33e1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_evaluations_user_job', 'evaluations', ['user_id', 'job_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_evaluations_user_job', 'evaluations', type_='unique')
    # ### end Alembic commands ###
